language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true

  allow_failures:
      - php: hhvm

  include:
    - php: 5.6
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 5.6
      env: COMPOSER_FLAG=--prefer-stable
    - php: 7.0
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 7.0
      env: COMPOSER_FLAG=--prefer-stable
    - php: 7.1
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 7.1
      env: COMPOSER_FLAG=--prefer-stable

script:
  # Composer
  - travis_retry composer install --no-interaction

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
